### ISSUE TITLE
Tab height not dynamically updating

### ISSUE THREAD

**Issue by runewolf7** [gijsroge/tabtab.js#9]
Hi there!!

Didn't know if this was still being maintained at all, but I have an issue on a client site that I need to get resolved as soon as possible. I built some accordions and such inside of Tabs on this page:

[http://pns.creativefuse.org/services/dogs/](http://pns.creativefuse.org/services/dogs/)

Not only does the tab height not flex to meet the needs of the content ( it is just defaulting to the height of the tallest tab as is evident when swapping between the Services and Surgeries tab ), but the tab height isn't flexing as accordions open and close. See attached.

Here are my settings for the tabs in question:

`$('.c-tabs').tabtab({

        tabMenu: '.c-tabs__menu',             // direct container of the tab menu items
        tabContent: '.c-tabs__panels',       // direct container of the tab content items
        next: '.c-tabs__controls__next',       // next slide trigger
        prev: '.c-tabs__controls__prev',       // previous slide trigger

        startSlide: 1,                      // starting slide on pageload
        arrows: false,                       // keyboard arrow navigation
        dynamicHeight: true,                // if true the height will dynamic and animated.
        useAnimations: true,                // disables animations.

        easing: 'ease',                     // http://julian.com/research/velocity/#easing
        speed: 450,                         // animation speed
        slideDelay: 200,                      // delay the animation
        perspective: 1200,                  // set 3D perspective
        transformOrigin: 'center',          // set the center point of the 3d animation
        perspectiveOrigin: '50% 50%',       // camera angle

        translateY: 0,                      // animate along the Y axis (val: px or ‘slide’)
        translateX: 1500,                     // animate along the X axis (val: px or ‘slide’)
        scale: 1,                           // animate scale (val: 0-2)
        rotateX: 0,                        // animate rotation (val: 0deg-360deg)
        rotateY: 0,                         // animate Y acces rotation (val: 0deg-360deg)
        skewY: 0,                           // animate Y skew (val: 0deg-360deg)
        skewX: 0,                           // animate X skew (val: 0deg-360deg)

    });`

Help would be much appreciated here :))

![screen shot 2017-08-15 at 1 30 28 pm](https://user-images.githubusercontent.com/17693193/29327691-f8077e0e-81bd-11e7-9518-b8bec3075249.png)

**Comment by gijsroge** [comment]
I don't have the time to assist you. But I can tell you there is no option to recalculate the height. I suggest using a different slider/tabs library.
